# build_italian_data.py - Compiles Italian CEFR A1-C2 vocabulary, verb conjugations, and themes
import json, os

def main():
    print("Building Italian CEFR & Conjugation database...")

    # 1. Base Core CEFR Lexicon with metadata
    # [word, lemma, cefr, pos, gender, english_meaning, optional_theme]
    core_lexicon = [
        # A1 - Saluti e base
        ("ciao", "ciao", "A1", "interj", "", "hello, goodbye (informal)", "Identità e Relazioni"),
        ("buongiorno", "buongiorno", "A1", "interj", "", "good morning, good day", "Identità e Relazioni"),
        ("buonasera", "buonasera", "A1", "interj", "", "good evening", "Identità e Relazioni"),
        ("buonanotte", "buonanotte", "A1", "interj", "", "goodnight", "Identità e Relazioni"),
        ("arrivederci", "arrivederci", "A1", "interj", "", "goodbye (formal/polite)", "Identità e Relazioni"),
        ("per favore", "per favore", "A1", "phrase", "", "please", "Identità e Relazioni"),
        ("per piacere", "per piacere", "A1", "phrase", "", "please", "Identità e Relazioni"),
        ("grazie", "grazie", "A1", "interj", "", "thank you, thanks", "Identità e Relazioni"),
        ("prego", "prego", "A1", "interj", "", "you're welcome, please go ahead", "Identità e Relazioni"),
        ("scusa", "scusa", "A1", "interj", "", "sorry, excuse me (informal)", "Identità e Relazioni"),
        ("scusi", "scusi", "A1", "interj", "", "excuse me (formal)", "Identità e Relazioni"),
        ("sì", "sì", "A1", "adv", "", "yes"),
        ("no", "no", "A1", "adv", "", "no"),
        ("non", "non", "A1", "adv", "", "not"),
        ("io", "io", "A1", "pron", "", "I"),
        ("tu", "tu", "A1", "pron", "", "you (informal)"),
        ("lui", "lui", "A1", "pron", "m", "he, him"),
        ("lei", "lei", "A1", "pron", "f", "she, her"),
        ("Lei", "Lei", "A1", "pron", "", "you (formal polite)"),
        ("noi", "noi", "A1", "pron", "pl", "we, us"),
        ("voi", "voi", "A1", "pron", "pl", "you all"),
        ("loro", "loro", "A1", "pron", "pl", "they, them"),
        ("mi", "mi", "A1", "pron", "", "me, to me, myself"),
        ("ti", "ti", "A1", "pron", "", "you, to you, yourself"),
        ("si", "si", "A1", "pron", "", "himself, herself, themselves, oneself"),
        ("ci", "ci", "A1", "pron", "", "us, to us; there; about it"),
        ("vi", "vi", "A1", "pron", "", "you all, to you all; there"),

        # Articoli
        ("il", "il", "A1", "art", "m.sg", "the (masculine singular before consonant)"),
        ("lo", "lo", "A1", "art", "m.sg", "the (masculine singular before s+cons, z, gn, etc.)"),
        ("la", "la", "A1", "art", "f.sg", "the (feminine singular)"),
        ("l'", "il", "A1", "art", "sg", "the (before vowel)"),
        ("i", "il", "A1", "art", "m.pl", "the (masculine plural)"),
        ("gli", "lo", "A1", "art", "m.pl", "the (masculine plural before vowel or s+cons)"),
        ("le", "la", "A1", "art", "f.pl", "the (feminine plural)"),
        ("un", "un", "A1", "art", "m.sg", "a, an (masculine)"),
        ("uno", "uno", "A1", "art", "m.sg", "a, an (masculine before s+cons, z, etc.)"),
        ("una", "una", "A1", "art", "f.sg", "a, an (feminine)"),
        ("un'", "una", "A1", "art", "f.sg", "a, an (feminine before vowel)"),

        # Dimostrativi
        ("questo", "questo", "A1", "pron/adj", "m.sg", "this"),
        ("questa", "questo", "A1", "pron/adj", "f.sg", "this"),
        ("questi", "questo", "A1", "pron/adj", "m.pl", "these"),
        ("queste", "questo", "A1", "pron/adj", "f.pl", "these"),
        ("quello", "quello", "A1", "pron/adj", "m.sg", "that"),
        ("quella", "quello", "A1", "pron/adj", "f.sg", "that"),
        ("quelli", "quello", "A1", "pron/adj", "m.pl", "those"),
        ("quelle", "quello", "A1", "pron/adj", "f.pl", "those"),
        ("quel", "quello", "A1", "adj", "m.sg", "that (before consonant)"),

        # Congiunzioni e interrogativi
        ("e", "e", "A1", "conj", "", "and"),
        ("ed", "e", "A1", "conj", "", "and (euphonic before vowel)"),
        ("o", "o", "A1", "conj", "", "or"),
        ("ma", "ma", "A1", "conj", "", "but"),
        ("perché", "perché", "A1", "conj/adv", "", "why; because"),
        ("se", "se", "A1", "conj", "", "if"),
        ("quando", "quando", "A1", "conj/adv", "", "when"),
        ("dove", "dove", "A1", "adv", "", "where"),
        ("come", "come", "A1", "adv", "", "how; like, as"),
        ("chi", "chi", "A1", "pron", "", "who, whom"),
        ("che", "che", "A1", "pron/conj", "", "what, which, that"),
        ("cosa", "cosa", "A1", "pron/n", "f", "what; thing"),
        ("quale", "quale", "A1", "pron/adj", "mf.sg", "which, what"),
        ("quali", "quale", "A1", "pron/adj", "mf.pl", "which, what (plural)"),
        ("quanto", "quanto", "A1", "pron/adj", "m.sg", "how much"),
        ("quanta", "quanto", "A1", "pron/adj", "f.sg", "how much"),
        ("quanti", "quanto", "A1", "pron/adj", "m.pl", "how many"),
        ("quante", "quanto", "A1", "pron/adj", "f.pl", "how many"),

        # Preposizioni
        ("di", "di", "A1", "prep", "", "of, from, about"),
        ("a", "a", "A1", "prep", "", "to, at, in"),
        ("ad", "a", "A1", "prep", "", "to, at (euphonic before vowel)"),
        ("da", "da", "A1", "prep", "", "from, by, since, at (someone's)"),
        ("in", "in", "A1", "prep", "", "in, into, to"),
        ("con", "con", "A1", "prep", "", "with"),
        ("su", "su", "A1", "prep", "", "on, upon, about"),
        ("per", "per", "A1", "prep", "", "for, in order to, through"),
        ("tra", "tra", "A1", "prep", "", "between, among, in (time)"),
        ("fra", "fra", "A1", "prep", "", "between, among, in (time)"),

        # Preposizioni articolate
        ("del", "del", "A1", "prep.art", "m.sg", "of the"),
        ("dello", "dello", "A1", "prep.art", "m.sg", "of the"),
        ("della", "della", "A1", "prep.art", "f.sg", "of the"),
        ("dell'", "dell'", "A1", "prep.art", "sg", "of the"),
        ("dei", "dei", "A1", "prep.art", "m.pl", "of the, some"),
        ("degli", "degli", "A1", "prep.art", "m.pl", "of the, some"),
        ("delle", "delle", "A1", "prep.art", "f.pl", "of the, some"),
        ("al", "al", "A1", "prep.art", "m.sg", "to the, at the"),
        ("allo", "allo", "A1", "prep.art", "m.sg", "to the, at the"),
        ("alla", "alla", "A1", "prep.art", "f.sg", "to the, at the"),
        ("all'", "all'", "A1", "prep.art", "sg", "to the, at the"),
        ("ai", "ai", "A1", "prep.art", "m.pl", "to the, at the"),
        ("agli", "agli", "A1", "prep.art", "m.pl", "to the, at the"),
        ("alle", "alle", "A1", "prep.art", "f.pl", "to the, at the"),
        ("dal", "dal", "A1", "prep.art", "m.sg", "from the, at the"),
        ("dallo", "dallo", "A1", "prep.art", "m.sg", "from the"),
        ("dalla", "dalla", "A1", "prep.art", "f.sg", "from the"),
        ("dall'", "dall'", "A1", "prep.art", "sg", "from the"),
        ("dai", "dai", "A1", "prep.art", "m.pl", "from the"),
        ("dagli", "dagli", "A1", "prep.art", "m.pl", "from the"),
        ("dalle", "dalle", "A1", "prep.art", "f.pl", "from the"),
        ("nel", "nel", "A1", "prep.art", "m.sg", "in the"),
        ("nello", "nello", "A1", "prep.art", "m.sg", "in the"),
        ("nella", "nella", "A1", "prep.art", "f.sg", "in the"),
        ("nell'", "nell'", "A1", "prep.art", "sg", "in the"),
        ("nei", "nei", "A1", "prep.art", "m.pl", "in the"),
        ("negli", "negli", "A1", "prep.art", "m.pl", "in the"),
        ("nelle", "nelle", "A1", "prep.art", "f.pl", "in the"),
        ("sul", "sul", "A1", "prep.art", "m.sg", "on the"),
        ("sullo", "sullo", "A1", "prep.art", "m.sg", "on the"),
        ("sulla", "sulla", "A1", "prep.art", "f.sg", "on the"),
        ("sull'", "sull'", "A1", "prep.art", "sg", "on the"),
        ("sui", "sui", "A1", "prep.art", "m.pl", "on the"),
        ("sugli", "sugli", "A1", "prep.art", "m.pl", "on the"),
        ("sulle", "sulle", "A1", "prep.art", "f.pl", "on the"),

        # Sostantivi A1
        ("casa", "casa", "A1", "n", "f", "house, home", "Identità e Relazioni"),
        ("tempo", "tempo", "A1", "n", "m", "time, weather"),
        ("anno", "anno", "A1", "n", "m", "year"),
        ("giorno", "giorno", "A1", "n", "m", "day"),
        ("notte", "notte", "A1", "n", "f", "night"),
        ("sera", "sera", "A1", "n", "f", "evening"),
        ("mattina", "mattina", "A1", "n", "f", "morning"),
        ("settimana", "settimana", "A1", "n", "f", "week"),
        ("mese", "mese", "A1", "n", "m", "month"),
        ("ora", "ora", "A1", "n/adv", "f", "hour; now"),
        ("uomo", "uomo", "A1", "n", "m", "man", "Identità e Relazioni"),
        ("donna", "donna", "A1", "n", "f", "woman", "Identità e Relazioni"),
        ("ragazzo", "ragazzo", "A1", "n", "m", "boy, young man", "Identità e Relazioni"),
        ("ragazza", "ragazza", "A1", "n", "f", "girl, young woman", "Identità e Relazioni"),
        ("bambino", "bambino", "A1", "n", "m", "child, boy", "Identità e Relazioni"),
        ("bambina", "bambino", "A1", "n", "f", "child, girl", "Identità e Relazioni"),
        ("padre", "padre", "A1", "n", "m", "father", "Identità e Relazioni"),
        ("madre", "madre", "A1", "n", "f", "mother", "Identità e Relazioni"),
        ("fratello", "fratello", "A1", "n", "m", "brother", "Identità e Relazioni"),
        ("sorella", "sorella", "A1", "n", "f", "sister", "Identità e Relazioni"),
        ("figlio", "figlio", "A1", "n", "m", "son", "Identità e Relazioni"),
        ("figlia", "figlio", "A1", "n", "f", "daughter", "Identità e Relazioni"),
        ("famiglia", "famiglia", "A1", "n", "f", "family", "Identità e Relazioni"),
        ("amico", "amico", "A1", "n", "m", "friend", "Identità e Relazioni"),
        ("amica", "amico", "A1", "n", "f", "friend (female)", "Identità e Relazioni"),
        ("lavoro", "lavoro", "A1", "n", "m", "work, job", "Organizzazione Sociale"),
        ("scuola", "scuola", "A1", "n", "f", "school", "Organizzazione Sociale"),
        ("università", "università", "A1", "n", "f", "university", "Organizzazione Sociale"),
        ("città", "città", "A1", "n", "f", "city, town", "Organizzazione Sociale"),
        ("paese", "paese", "A1", "n", "m", "country, village, small town", "Organizzazione Sociale"),
        ("strada", "strada", "A1", "n", "f", "street, road"),
        ("piazza", "piazza", "A1", "n", "f", "square, plaza", "Arte e Creatività"),
        ("mare", "mare", "A1", "n", "m", "sea", "Scienza e Ambiente"),
        ("montagna", "montagna", "A1", "n", "f", "mountain", "Scienza e Ambiente"),
        ("cibo", "cibo", "A1", "n", "m", "food", "Esperienze e Viaggi"),
        ("acqua", "acqua", "A1", "n", "f", "water", "Scienza e Ambiente"),
        ("vino", "vino", "A1", "n", "m", "wine", "Esperienze e Viaggi"),
        ("birra", "birra", "A1", "n", "f", "beer", "Esperienze e Viaggi"),
        ("pane", "pane", "A1", "n", "m", "bread", "Esperienze e Viaggi"),
        ("caffè", "caffè", "A1", "n", "m", "coffee, café", "Esperienze e Viaggi"),
        ("latte", "latte", "A1", "n", "m", "milk", "Esperienze e Viaggi"),
        ("pasta", "pasta", "A1", "n", "f", "pasta", "Esperienze e Viaggi"),
        ("pizza", "pizza", "A1", "n", "f", "pizza", "Esperienze e Viaggi"),
        ("gelato", "gelato", "A1", "n", "m", "ice cream, gelato", "Esperienze e Viaggi"),
        ("libro", "libro", "A1", "n", "m", "book", "Arte e Creatività"),
        ("musica", "musica", "A1", "n", "f", "music", "Arte e Creatività"),
        ("macchina", "macchina", "A1", "n", "f", "car, machine"),
        ("treno", "treno", "A1", "n", "m", "train", "Esperienze e Viaggi"),
        ("nome", "nome", "A1", "n", "m", "name", "Identità e Relazioni"),
        ("persona", "persona", "A1", "n", "f", "person", "Identità e Relazioni"),
        ("gente", "gente", "A1", "n", "f", "people", "Identità e Relazioni"),
        ("vita", "vita", "A1", "n", "f", "life", "Identità e Relazioni"),
        ("mondo", "mondo", "A1", "n", "m", "world", "Scienza e Ambiente"),

        # Aggettivi A1
        ("bello", "bello", "A1", "adj", "m.sg", "beautiful, handsome, nice", "Arte e Creatività"),
        ("bella", "bello", "A1", "adj", "f.sg", "beautiful, pretty", "Arte e Creatività"),
        ("belli", "bello", "A1", "adj", "m.pl", "beautiful", "Arte e Creatività"),
        ("belle", "bello", "A1", "adj", "f.pl", "beautiful", "Arte e Creatività"),
        ("buono", "buono", "A1", "adj", "m.sg", "good, tasty"),
        ("buona", "buono", "A1", "adj", "f.sg", "good"),
        ("buoni", "buono", "A1", "adj", "m.pl", "good"),
        ("buone", "buono", "A1", "adj", "f.pl", "good"),
        ("grande", "grande", "A1", "adj", "mf.sg", "big, great, large"),
        ("grandi", "grande", "A1", "adj", "mf.pl", "big, great"),
        ("piccolo", "piccolo", "A1", "adj", "m.sg", "small, little"),
        ("piccola", "piccolo", "A1", "adj", "f.sg", "small, little"),
        ("piccoli", "piccolo", "A1", "adj", "m.pl", "small"),
        ("piccole", "piccolo", "A1", "adj", "f.pl", "small"),
        ("nuovo", "nuovo", "A1", "adj", "m.sg", "new"),
        ("nuova", "nuovo", "A1", "adj", "f.sg", "new"),
        ("nuovi", "nuovo", "A1", "adj", "m.pl", "new"),
        ("nuove", "nuovo", "A1", "adj", "f.pl", "new"),
        ("vecchio", "vecchio", "A1", "adj", "m.sg", "old"),
        ("vecchia", "vecchio", "A1", "adj", "f.sg", "old"),
        ("vecchi", "vecchio", "A1", "adj", "m.pl", "old"),
        ("vecchie", "vecchio", "A1", "adj", "f.pl", "old"),
        ("caldo", "caldo", "A1", "adj/n", "m", "hot, warm"),
        ("freddo", "freddo", "A1", "adj/n", "m", "cold"),
        ("facile", "facile", "A1", "adj", "mf.sg", "easy"),
        ("difficile", "difficile", "A1", "adj", "mf.sg", "difficult, hard"),
        ("felice", "felice", "A1", "adj", "mf.sg", "happy", "Identità e Relazioni"),
        ("triste", "triste", "A1", "adj", "mf.sg", "sad", "Identità e Relazioni"),
        ("alto", "alto", "A1", "adj", "m.sg", "tall, high"),
        ("basso", "basso", "A1", "adj", "m.sg", "short, low"),
        ("primo", "primo", "A1", "adj", "m.sg", "first"),
        ("prima", "primo", "A1", "adj/adv", "f.sg", "first; before"),
        ("primi", "primo", "A1", "adj", "m.pl", "first"),
        ("prime", "primo", "A1", "adj", "f.pl", "first"),
        ("ultimo", "ultimo", "A1", "adj", "m.sg", "last, final"),
        ("ultima", "ultimo", "A1", "adj", "f.sg", "last, final"),
        ("stesso", "stesso", "A1", "adj/pron", "m.sg", "same, himself"),
        ("stessa", "stesso", "A1", "adj/pron", "f.sg", "same, herself"),
        ("altro", "altro", "A1", "adj/pron", "m.sg", "other, another"),
        ("altra", "altro", "A1", "adj/pron", "f.sg", "other, another"),
        ("altri", "altro", "A1", "adj/pron", "m.pl", "others"),
        ("altre", "altro", "A1", "adj/pron", "f.pl", "others"),
        ("tutto", "tutto", "A1", "adj/pron", "m.sg", "all, whole, everything"),
        ("tutta", "tutto", "A1", "adj", "f.sg", "all, whole"),
        ("tutti", "tutto", "A1", "adj/pron", "m.pl", "everyone, all"),
        ("tutte", "tutto", "A1", "adj/pron", "f.pl", "all (feminine)"),
        ("molto", "molto", "A1", "adj/adv", "m.sg", "much, very, a lot"),
        ("molti", "molto", "A1", "adj/pron", "m.pl", "many"),
        ("molte", "molto", "A1", "adj/pron", "f.pl", "many"),
        ("poco", "poco", "A1", "adj/adv", "m.sg", "little, few, not much"),
        ("pochi", "poco", "A1", "adj/pron", "m.pl", "few"),
        ("poche", "poco", "A1", "adj/pron", "f.pl", "few"),
        ("italiano", "italiano", "A1", "adj/n", "m", "Italian", "Identità e Relazioni"),
        ("italiana", "italiano", "A1", "adj/n", "f", "Italian (female)", "Identità e Relazioni"),
        ("italiani", "italiano", "A1", "adj/n", "m.pl", "Italians", "Identità e Relazioni"),
        ("italiane", "italiano", "A1", "adj/n", "f.pl", "Italian (women)", "Identità e Relazioni"),

        # A2 - Quotidiano, Viaggi, Commercio, Salute
        ("viaggio", "viaggio", "A2", "n", "m", "trip, journey, travel", "Esperienze e Viaggi"),
        ("viaggiare", "viaggiare", "A2", "v", "", "to travel", "Esperienze e Viaggi"),
        ("vacanza", "vacanza", "A2", "n", "f", "holiday, vacation", "Esperienze e Viaggi"),
        ("vacanze", "vacanza", "A2", "n", "f.pl", "holidays, vacation", "Esperienze e Viaggi"),
        ("comprare", "comprare", "A2", "v", "", "to buy, purchase", "Organizzazione Sociale"),
        ("vendere", "vendere", "A2", "v", "", "to sell", "Organizzazione Sociale"),
        ("pagare", "pagare", "A2", "v", "", "to pay", "Organizzazione Sociale"),
        ("costare", "costare", "A2", "v", "", "to cost", "Organizzazione Sociale"),
        ("prezzo", "prezzo", "A2", "n", "m", "price, cost", "Organizzazione Sociale"),
        ("soldi", "soldi", "A2", "n", "m.pl", "money", "Organizzazione Sociale"),
        ("denaro", "denaro", "A2", "n", "m", "money", "Organizzazione Sociale"),
        ("conto", "conto", "A2", "n", "m", "bill, account", "Esperienze e Viaggi"),
        ("negozio", "negozio", "A2", "n", "m", "shop, store", "Organizzazione Sociale"),
        ("mercato", "mercato", "A2", "n", "m", "market", "Organizzazione Sociale"),
        ("vestito", "vestito", "A2", "n", "m", "dress, suit, clothes", "Identità e Relazioni"),
        ("scarpa", "scarpa", "A2", "n", "f", "shoe", "Identità e Relazioni"),
        ("scarpe", "scarpa", "A2", "n", "f.pl", "shoes", "Identità e Relazioni"),
        ("stazione", "stazione", "A2", "n", "f", "station, train station", "Esperienze e Viaggi"),
        ("aeroporto", "aeroporto", "A2", "n", "m", "airport", "Esperienze e Viaggi"),
        ("aereo", "aereo", "A2", "n", "m", "airplane, plane", "Esperienze e Viaggi"),
        ("autobus", "autobus", "A2", "n", "m", "bus", "Esperienze e Viaggi"),
        ("biglietto", "biglietto", "A2", "n", "m", "ticket", "Esperienze e Viaggi"),
        ("albergo", "albergo", "A2", "n", "m", "hotel", "Esperienze e Viaggi"),
        ("hotel", "hotel", "A2", "n", "m", "hotel", "Esperienze e Viaggi"),
        ("ristorante", "ristorante", "A2", "n", "m", "restaurant", "Esperienze e Viaggi"),
        ("menu", "menu", "A2", "n", "m", "menu", "Esperienze e Viaggi"),
        ("cameriere", "cameriere", "A2", "n", "m", "waiter", "Esperienze e Viaggi"),
        ("colazione", "colazione", "A2", "n", "f", "breakfast", "Esperienze e Viaggi"),
        ("pranzo", "pranzo", "A2", "n", "m", "lunch", "Esperienze e Viaggi"),
        ("cena", "cena", "A2", "n", "f", "dinner", "Esperienze e Viaggi"),
        ("salute", "salute", "A2", "n", "f", "health", "Identità e Relazioni"),
        ("medico", "medico", "A2", "n", "m", "doctor, physician", "Identità e Relazioni"),
        ("ospedale", "ospedale", "A2", "n", "m", "hospital", "Organizzazione Sociale"),
        ("farmacia", "farmacia", "A2", "n", "f", "pharmacy", "Organizzazione Sociale"),
        ("medicina", "medicina", "A2", "n", "f", "medicine", "Organizzazione Sociale"),
        ("malato", "malato", "A2", "adj/n", "m", "sick, patient", "Identità e Relazioni"),
        ("febbre", "febbre", "A2", "n", "f", "fever", "Identità e Relazioni"),
        ("dolore", "dolore", "A2", "n", "m", "pain, ache", "Identità e Relazioni"),
        ("corpo", "corpo", "A2", "n", "m", "body", "Identità e Relazioni"),
        ("testa", "testa", "A2", "n", "f", "head", "Identità e Relazioni"),
        ("mano", "mano", "A1", "n", "f", "hand", "Identità e Relazioni"),
        ("mani", "mano", "A1", "n", "f.pl", "hands", "Identità e Relazioni"),
        ("occhio", "occhio", "A1", "n", "m", "eye", "Identità e Relazioni"),
        ("occhi", "occhio", "A1", "n", "m.pl", "eyes", "Identità e Relazioni"),
        ("bocca", "bocca", "A2", "n", "f", "mouth", "Identità e Relazioni"),
        ("cuore", "cuore", "A2", "n", "m", "heart", "Identità e Relazioni"),
        ("piede", "piede", "A2", "n", "m", "foot", "Identità e Relazioni"),
        ("ieri", "ieri", "A1", "adv", "", "yesterday"),
        ("oggi", "oggi", "A1", "adv", "", "today"),
        ("domani", "domani", "A1", "adv", "", "tomorrow"),
        ("presto", "presto", "A2", "adv", "", "early, soon"),
        ("tardi", "tardi", "A2", "adv", "", "late"),
        ("subito", "subito", "A2", "adv", "", "immediately, right away"),
        ("sempre", "sempre", "A1", "adv", "", "always"),
        ("spesso", "spesso", "A2", "adv", "", "often"),
        ("mai", "mai", "A1", "adv", "", "never, ever"),
        ("già", "già", "A2", "adv", "", "already"),
        ("ancora", "ancora", "A2", "adv", "", "still, yet, again"),
        ("anche", "anche", "A1", "adv", "", "also, too, as well"),
        ("neanche", "neanche", "A2", "adv", "", "not even, neither"),
        ("nemmeno", "nemmeno", "A2", "adv", "", "not even, neither"),
        ("forse", "forse", "A2", "adv", "", "maybe, perhaps"),
        ("insieme", "insieme", "A2", "adv", "", "together", "Identità e Relazioni"),
        ("solo", "solo", "A1", "adj/adv", "m.sg", "alone; only"),
        ("solamente", "solamente", "A2", "adv", "", "only, solely"),
        ("vicino", "vicino", "A1", "adj/adv", "m.sg", "near, close"),
        ("lontano", "lontano", "A1", "adj/adv", "m.sg", "far, distant"),
        ("sopra", "sopra", "A2", "prep/adv", "", "above, over, on"),
        ("sotto", "sotto", "A2", "prep/adv", "", "under, below"),
        ("davanti", "davanti", "A2", "prep/adv", "", "in front of"),
        ("dietro", "dietro", "A2", "prep/adv", "", "behind"),
        ("dentro", "dentro", "A2", "prep/adv", "", "inside"),
        ("fuori", "fuori", "A2", "prep/adv", "", "outside"),
        ("prima", "prima", "A1", "adv/prep", "", "before, earlier"),
        ("dopo", "dopo", "A1", "adv/prep", "", "after, later"),
        ("poi", "poi", "A1", "adv", "", "then, later"),
        ("allora", "allora", "A2", "adv", "", "then, at that time, so"),

        # B1 - Società, Opinioni, Ambiente, Lavoro
        ("sviluppo", "sviluppo", "B1", "n", "m", "development, growth", "Organizzazione Sociale"),
        ("sviluppare", "sviluppare", "B1", "v", "", "to develop, expand", "Organizzazione Sociale"),
        ("opinione", "opinione", "B1", "n", "f", "opinion, view", "Identità e Relazioni"),
        ("credere", "credere", "B1", "v", "", "to believe, think", "Identità e Relazioni"),
        ("pensare", "pensare", "B1", "v", "", "to think, intend", "Identità e Relazioni"),
        ("pensiero", "pensiero", "B1", "n", "m", "thought, thinking", "Identità e Relazioni"),
        ("sembrare", "sembrare", "B1", "v", "", "to seem, appear"),
        ("sperare", "sperare", "B1", "v", "", "to hope", "Identità e Relazioni"),
        ("speranza", "speranza", "B1", "n", "f", "hope", "Identità e Relazioni"),
        ("dubitare", "dubitare", "B1", "v", "", "to doubt"),
        ("dubbio", "dubbio", "B1", "n", "m", "doubt"),
        ("tuttavia", "tuttavia", "B1", "adv/conj", "", "however, nevertheless"),
        ("sebbene", "sebbene", "B1", "conj", "", "although, even though"),
        ("benché", "benché", "B1", "conj", "", "although, though"),
        ("affinché", "affinché", "B1", "conj", "", "so that, in order that"),
        ("invece", "invece", "B1", "adv", "", "instead, on the contrary"),
        ("inoltre", "inoltre", "B1", "adv", "", "furthermore, moreover"),
        ("infatti", "infatti", "B1", "adv", "", "in fact, indeed"),
        ("quindi", "quindi", "B1", "adv/conj", "", "therefore, so"),
        ("perciò", "perciò", "B1", "adv/conj", "", "therefore, for this reason"),
        ("probabilmente", "probabilmente", "B1", "adv", "", "probably, likely"),
        ("purtroppo", "purtroppo", "B1", "adv", "", "unfortunately, alas"),
        ("finalmente", "finalmente", "B1", "adv", "", "finally, at last"),
        ("successo", "successo", "B1", "n", "m", "success; happened", "Esperienze e Viaggi"),
        ("fallimento", "fallimento", "B1", "n", "m", "failure, bankruptcy", "Esperienze e Viaggi"),
        ("obiettivo", "obiettivo", "B1", "n", "m", "objective, goal, target", "Esperienze e Viaggi"),
        ("scopo", "scopo", "B1", "n", "m", "purpose, aim", "Esperienze e Viaggi"),
        ("scelta", "scelta", "B1", "n", "f", "choice, option", "Identità e Relazioni"),
        ("decidere", "decidere", "B1", "v", "", "to decide"),
        ("decisione", "decisione", "B1", "n", "f", "decision"),
        ("problema", "problema", "B1", "n", "m", "problem, issue"),
        ("soluzione", "soluzione", "B1", "n", "f", "solution, remedy"),
        ("risolvere", "risolvere", "B1", "v", "", "to resolve, solve"),
        ("proteggere", "proteggere", "B1", "v", "", "to protect, shield", "Scienza e Ambiente"),
        ("protezione", "protezione", "B1", "n", "f", "protection", "Scienza e Ambiente"),
        ("ambiente", "ambiente", "B1", "n", "m", "environment, surroundings", "Scienza e Ambiente"),
        ("natura", "natura", "B1", "n", "f", "nature", "Scienza e Ambiente"),
        ("diritto", "diritto", "B1", "n/adj", "m", "right, law; straight", "Organizzazione Sociale"),
        ("legge", "legge", "B1", "n", "f", "law, statute", "Organizzazione Sociale"),
        ("giustizia", "giustizia", "B1", "n", "f", "justice, fairness", "Organizzazione Sociale"),
        ("libertà", "libertà", "B1", "n", "f", "freedom, liberty", "Organizzazione Sociale"),
        ("governo", "governo", "B1", "n", "m", "government", "Organizzazione Sociale"),
        ("società", "società", "B1", "n", "f", "society, company", "Organizzazione Sociale"),
        ("cultura", "cultura", "B1", "n", "f", "culture", "Arte e Creatività"),
        ("educazione", "educazione", "B1", "n", "f", "education, upbringing", "Organizzazione Sociale"),
        ("esperienza", "esperienza", "B1", "n", "f", "experience", "Esperienze e Viaggi"),
        ("opportunità", "opportunità", "B1", "n", "f", "opportunity, chance", "Esperienze e Viaggi"),
        ("possibilità", "possibilità", "B1", "n", "f", "possibility, opportunity"),
        ("vantaggio", "vantaggio", "B1", "n", "m", "advantage, benefit"),
        ("svantaggio", "svantaggio", "B1", "n", "m", "disadvantage, drawback"),
        ("consiglio", "consiglio", "B1", "n", "m", "advice, council"),
        ("consigliare", "consigliare", "B1", "v", "", "to advise, recommend"),
        ("suggerire", "suggerire", "B1", "v", "", "to suggest, hint"),
        ("spiegare", "spiegare", "B1", "v", "", "to explain, unfold"),
        ("informazione", "informazione", "B1", "n", "f", "information", "Organizzazione Sociale"),
        ("notizia", "notizia", "B1", "n", "f", "news item, news", "Organizzazione Sociale"),
        ("comunicazione", "comunicazione", "B1", "n", "f", "communication", "Organizzazione Sociale"),
        ("condividere", "condividere", "B1", "v", "", "to share", "Identità e Relazioni"),
        ("evitare", "evitare", "B1", "v", "", "to avoid, shun"),
        ("raggiungere", "raggiungere", "B1", "v", "", "to reach, achieve, attain"),
        ("migliorare", "migliorare", "B1", "v", "", "to improve, enhance"),
        ("peggiorare", "peggiorare", "B1", "v", "", "to worsen, deteriorate"),

        # B2 - Complessità, Argomentazione, Cultura, Scienza
        ("sostenibilità", "sostenibilità", "B2", "n", "f", "sustainability", "Scienza e Ambiente"),
        ("sostenibile", "sostenibile", "B2", "adj", "mf.sg", "sustainable", "Scienza e Ambiente"),
        ("biodiversità", "biodiversità", "B2", "n", "f", "biodiversity", "Scienza e Ambiente"),
        ("innovazione", "innovazione", "B2", "n", "f", "innovation", "Scienza e Ambiente"),
        ("innovativo", "innovativo", "B2", "adj", "m.sg", "innovative", "Scienza e Ambiente"),
        ("ricerca", "ricerca", "B2", "n", "f", "research, search", "Scienza e Ambiente"),
        ("ricercatore", "ricercatore", "B2", "n", "m", "researcher", "Scienza e Ambiente"),
        ("tecnologia", "tecnologia", "B2", "n", "f", "technology", "Scienza e Ambiente"),
        ("scientifico", "scientifico", "B2", "adj", "m.sg", "scientific", "Scienza e Ambiente"),
        ("complesso", "complesso", "B2", "adj/n", "m", "complex, intricate; complex"),
        ("prospettiva", "prospettiva", "B2", "n", "f", "perspective, outlook", "Arte e Creatività"),
        ("approccio", "approccio", "B2", "n", "m", "approach, method"),
        ("tendenza", "tendenza", "B2", "n", "f", "trend, tendency"),
        ("dibattito", "dibattito", "B2", "n", "m", "debate, discussion", "Organizzazione Sociale"),
        ("consenso", "consenso", "B2", "n", "m", "consensus, agreement", "Organizzazione Sociale"),
        ("controversia", "controversia", "B2", "n", "f", "controversy, dispute", "Organizzazione Sociale"),
        ("discrepanza", "discrepanza", "B2", "n", "f", "discrepancy, divergence"),
        ("priorità", "priorità", "B2", "n", "f", "priority"),
        ("promuovere", "promuovere", "B2", "v", "", "to promote, foster"),
        ("valorizzare", "valorizzare", "B2", "v", "", "to enhance, appreciate, valorize", "Arte e Creatività"),
        ("rafforzare", "rafforzare", "B2", "v", "", "to strengthen, reinforce"),
        ("consolidare", "consolidare", "B2", "v", "", "to consolidate, firm up"),
        ("sottolineare", "sottolineare", "B2", "v", "", "to underline, emphasize"),
        ("evidenziare", "evidenziare", "B2", "v", "", "to highlight, point out"),
        ("mitigare", "mitigare", "B2", "v", "", "to mitigate, ease", "Scienza e Ambiente"),
        ("favorire", "favorire", "B2", "v", "", "to favor, facilitate"),
        ("comportare", "comportare", "B2", "v", "", "to entail, involve, imply"),
        ("implicare", "implicare", "B2", "v", "", "to imply, involve"),
        ("presupporre", "presupporre", "B2", "v", "", "to presuppose, assume"),
        ("svolgere", "svolgere", "B2", "v", "", "to carry out, perform, develop"),
        ("affrontare", "affrontare", "B2", "v", "", "to confront, tackle, face"),
        ("superare", "superare", "B2", "v", "", "to overcome, exceed, surpass"),
        ("sfida", "sfida", "B2", "n", "f", "challenge, defiance"),
        ("paradosso", "paradosso", "B2", "n", "m", "paradox"),
        ("ipotesi", "ipotesi", "B2", "n", "f", "hypothesis, assumption", "Scienza e Ambiente"),
        ("premessa", "premessa", "B2", "n", "f", "premise, preface"),
        ("vulnerabilità", "vulnerabilità", "B2", "n", "f", "vulnerability"),
        ("vulnerabile", "vulnerabile", "B2", "adj", "mf.sg", "vulnerable"),
        ("imprescindibile", "imprescindibile", "B2", "adj", "mf.sg", "essential, indispensable"),
        ("fondamentale", "fondamentale", "B2", "adj", "mf.sg", "fundamental, pivotal"),
        ("rilevante", "rilevante", "B2", "adj", "mf.sg", "relevant, significant"),
        ("notevole", "notevole", "B2", "adj", "mf.sg", "remarkable, notable"),
        ("contemporaneo", "contemporaneo", "B2", "adj", "m.sg", "contemporary", "Arte e Creatività"),
        ("globale", "globale", "B2", "adj", "mf.sg", "global, worldwide", "Scienza e Ambiente"),
        ("sfumatura", "sfumatura", "B2", "n", "f", "nuance, shade, overtone", "Arte e Creatività"),
        ("patrimonio", "patrimonio", "B2", "n", "m", "heritage, assets", "Arte e Creatività"),

        # C1 - Lessico Formale, Filosofico, Accademico
        ("sviscerare", "sviscerare", "C1", "v", "", "to analyze thoroughly, examine in depth"),
        ("dirimere", "dirimere", "C1", "v", "", "to resolve, settle (a dispute)"),
        ("scaturire", "scaturire", "C1", "v", "", "to stem from, arise, spring"),
        ("affrancarsi", "affrancarsi", "C1", "v", "", "to free oneself, liberate oneself"),
        ("corroborare", "corroborare", "C1", "v", "", "to corroborate, reinforce, confirm"),
        ("disquisire", "disquisire", "C1", "v", "", "to discourse, expound at length"),
        ("perorare", "perorare", "C1", "v", "", "to plead, advocate passionately"),
        ("preconizzare", "preconizzare", "C1", "v", "", "to advocate, foretell, commend"),
        ("reiterare", "reiterare", "C1", "v", "", "to reiterate, repeat"),
        ("sottendere", "sottendere", "C1", "v", "", "to underlie, subtend"),
        ("confutare", "confutare", "C1", "v", "", "to refute, disprove"),
        ("coadiuvare", "coadiuvare", "C1", "v", "", "to assist, aid, cooperate"),
        ("sminuire", "sminuire", "C1", "v", "", "to diminish, belittle, downplay"),
        ("minare", "minare", "C1", "v", "", "to undermine, erode"),
        ("fugare", "fugare", "C1", "v", "", "to dispel, banish (doubts)"),
        ("catalizzare", "catalizzare", "C1", "v", "", "to catalyze, prompt"),
        ("sfaccettatura", "sfaccettatura", "C1", "n", "f", "facet, aspect, angle"),
        ("congiuntura", "congiuntura", "C1", "n", "f", "economic juncture, circumstance"),
        ("reticenza", "reticenza", "C1", "n", "f", "reluctance, secrecy, reticence"),
        ("lungimiranza", "lungimiranza", "C1", "n", "f", "foresight, vision"),
        ("tracotanza", "tracotanza", "C1", "n", "f", "arrogance, hubris"),
        ("acquiescenza", "acquiescenza", "C1", "n", "f", "acquiescence, compliance"),
        ("vicissitudine", "vicissitudine", "C1", "n", "f", "vicissitude, hardship"),
        ("peculiarità", "peculiarità", "C1", "n", "f", "peculiarity, unique feature"),
        ("paradigma", "paradigma", "C1", "n", "m", "paradigm, model"),
        ("retaggio", "retaggio", "C1", "n", "m", "legacy, heritage", "Arte e Creatività"),
        ("compendio", "compendio", "C1", "n", "m", "compendium, epitome, summary"),
        ("dicotomia", "dicotomia", "C1", "n", "f", "dichotomy, division"),
        ("prodromo", "prodromo", "C1", "n", "m", "early sign, precursor, prodrome"),
        ("foriero", "foriero", "C1", "adj", "m.sg", "harbinger of, bringing, portentous"),
        ("pervasivo", "pervasivo", "C1", "adj", "m.sg", "pervasive, widespread"),
        ("poliedrico", "poliedrico", "C1", "adj", "m.sg", "versatile, multifaceted"),
        ("capillare", "capillare", "C1", "adj", "mf.sg", "widespread, meticulous, capillary"),
        ("meticoloso", "meticoloso", "C1", "adj", "m.sg", "meticulous, painstaking"),
        ("encomiabile", "encomiabile", "C1", "adj", "mf.sg", "praiseworthy, commendable"),
        ("deleterio", "deleterio", "C1", "adj", "m.sg", "deleterious, harmful"),
        ("capzioso", "capzioso", "C1", "adj", "m.sg", "specious, deceptive, captious"),
        ("olistico", "olistico", "C1", "adj", "m.sg", "holistic, comprehensive"),

        # C2 - Finezza Stilistica, Letteraria e Concettuale
        ("pletorico", "pletorico", "C2", "adj", "m.sg", "plethoric, bloated, redundant"),
        ("ontologico", "ontologico", "C2", "adj", "m.sg", "ontological"),
        ("apollineo", "apollineo", "C2", "adj", "m.sg", "Apollonian, serene, balanced", "Arte e Creatività"),
        ("dionisiaco", "dionisiaco", "C2", "adj", "m.sg", "Dionysian, ecstatic, passionate", "Arte e Creatività"),
        ("solipsismo", "solipsismo", "C2", "n", "m", "solipsism, extreme egocentric isolation"),
        ("ieratico", "ieratico", "C2", "adj", "m.sg", "hieratic, solemn, priestly"),
        ("sesquipedale", "sesquipedale", "C2", "adj", "mf.sg", "sesquipedalian, excessively long-winded"),
        ("tautologia", "tautologia", "C2", "n", "f", "tautology, redundant truth"),
        ("escatologico", "escatologico", "C2", "adj", "m.sg", "eschatological, end-of-times"),
        ("anamnesi", "anamnesi", "C2", "n", "f", "anamnesis, medical history, recollection"),
        ("ipostatizzare", "ipostatizzare", "C2", "v", "", "to hypostatize, personify an abstraction"),
        ("palinodia", "palinodia", "C2", "n", "f", "palinode, formal retraction, recantation"),
        ("abbacinante", "abbacinante", "C2", "adj", "mf.sg", "dazzling, blinding"),
        ("corrusco", "corrusco", "C2", "adj", "m.sg", "glittering, flashing, radiant"),
        ("gnomico", "gnomico", "C2", "adj", "m.sg", "gnomic, aphoristic, pithy"),
        ("lapidario", "lapidario", "C2", "adj", "m.sg", "lapidary, concise and memorable"),
        ("apodittico", "apodittico", "C2", "adj", "m.sg", "apodictic, undeniably certain"),
        ("eristico", "eristico", "C2", "adj", "m.sg", "eristic, disputatious"),
        ("anfibologia", "anfibologia", "C2", "n", "f", "amphibology, grammatical ambiguity"),
        ("spocchia", "spocchia", "C2", "n", "f", "smugness, conceit, arrogance"),
        ("pusillanime", "pusillanime", "C2", "adj", "mf.sg", "pusillanimous, cowardly"),
        ("protervia", "protervia", "C2", "n", "f", "arrogant insolence, defiance"),
        ("abulia", "abulia", "C2", "n", "f", "apathy, total lack of willpower"),
        ("prosopopea", "prosopopea", "C2", "n", "f", "prosopopoeia, personification, pompous demeanor"),
        ("quisquilia", "quisquilia", "C2", "n", "f", "trifle, petty triviality"),
        ("bazzecola", "bazzecola", "C2", "n", "f", "trifle, bagatelle, mere detail"),
        ("ghiribizzo", "ghiribizzo", "C2", "n", "m", "whim, fancy, caprice")
    ]

    # Convert core list into dict
    word_dict = {}
    for item in core_lexicon:
        w = item[0]
        lemma = item[1]
        cefr = item[2]
        pos = item[3]
        gender = item[4]
        meaning = item[5]
        theme = item[6] if len(item) > 6 else ""

        entry = {
            "l": lemma,
            "c": cefr,
            "p": pos,
            "g": gender,
            "m": meaning
        }
        if theme:
            entry["theme"] = theme
        word_dict[w.lower()] = entry

    # 2. Comprehensive Italian Verb Paradigms
    # Key irregulars & representative models
    verbs_data = [
        {
            "infinitive": "essere",
            "cefr": "A1",
            "auxiliary": "essere",
            "meaning": "to be, exist",
            "presente": ["sono", "sei", "è", "siamo", "siete", "sono"],
            "imperfetto": ["ero", "eri", "era", "eravamo", "eravate", "erano"],
            "passato_prossimo": ["sono stato", "sei stato", "è stato", "siamo stati", "siete stati", "sono stati"],
            "futuro": ["sarò", "sarai", "sarà", "saremo", "sarete", "saranno"],
            "condizionale": ["sarei", "saresti", "sarebbe", "saremmo", "sareste", "sarebbero"],
            "congiuntivo_pres": ["sia", "sia", "sia", "siamo", "siate", "siano"],
            "congiuntivo_imp": ["fossi", "fossi", "fosse", "fossimo", "foste", "fossero"],
            "imperativo": ["-", "sii", "sia", "siamo", "siate", "siano"],
            "gerundio": "essendo",
            "participio_passato": "stato"
        },
        {
            "infinitive": "avere",
            "cefr": "A1",
            "auxiliary": "avere",
            "meaning": "to have",
            "presente": ["ho", "hai", "ha", "abbiamo", "avete", "hanno"],
            "imperfetto": ["avevo", "avevi", "aveva", "avevamo", "avevate", "avevano"],
            "passato_prossimo": ["ho avuto", "hai avuto", "ha avuto", "abbiamo avuto", "avete avuto", "hanno avuto"],
            "futuro": ["avrò", "avrai", "avrà", "avremo", "avrete", "avranno"],
            "condizionale": ["avrei", "avresti", "avrebbe", "avremmo", "avreste", "avrebbero"],
            "congiuntivo_pres": ["abbia", "abbia", "abbia", "abbiamo", "abbiate", "abbiano"],
            "congiuntivo_imp": ["avessi", "avessi", "avesse", "avessimo", "aveste", "avessero"],
            "imperativo": ["-", "abbi", "abbia", "abbiamo", "abbiate", "abbiano"],
            "gerundio": "avendo",
            "participio_passato": "avuto"
        },
        {
            "infinitive": "andare",
            "cefr": "A1",
            "auxiliary": "essere",
            "meaning": "to go",
            "presente": ["vado", "vai", "va", "andiamo", "andate", "vanno"],
            "imperfetto": ["andavo", "andavi", "andava", "andavamo", "andavate", "andavano"],
            "passato_prossimo": ["sono andato", "sei andato", "è andato", "siamo andati", "siete andati", "sono andati"],
            "futuro": ["andrò", "andrai", "andrà", "andremo", "andrete", "andranno"],
            "condizionale": ["andrei", "andresti", "andrebbe", "andremmo", "andreste", "andrebbero"],
            "congiuntivo_pres": ["vada", "vada", "vada", "andiamo", "andiate", "vadano"],
            "congiuntivo_imp": ["andassi", "andassi", "andasse", "andassimo", "andaste", "andassero"],
            "imperativo": ["-", "va'", "vada", "andiamo", "andate", "vadano"],
            "gerundio": "andando",
            "participio_passato": "andato"
        },
        {
            "infinitive": "fare",
            "cefr": "A1",
            "auxiliary": "avere",
            "meaning": "to do, make",
            "presente": ["faccio", "fai", "fa", "facciamo", "fate", "fanno"],
            "imperfetto": ["facevo", "facevi", "faceva", "facevamo", "facevate", "facevano"],
            "passato_prossimo": ["ho fatto", "hai fatto", "ha fatto", "abbiamo fatto", "avete fatto", "hanno fatto"],
            "futuro": ["farò", "farai", "farà", "faremo", "farete", "faranno"],
            "condizionale": ["farei", "faresti", "farebbe", "faremmo", "fareste", "farebbero"],
            "congiuntivo_pres": ["faccia", "faccia", "faccia", "facciamo", "facciate", "facciano"],
            "congiuntivo_imp": ["facessi", "facessi", "facesse", "facessimo", "faceste", "facessero"],
            "imperativo": ["-", "fa'", "faccia", "facciamo", "fate", "facciano"],
            "gerundio": "facendo",
            "participio_passato": "fatto"
        },
        {
            "infinitive": "venire",
            "cefr": "A1",
            "auxiliary": "essere",
            "meaning": "to come",
            "presente": ["vengo", "vieni", "viene", "veniamo", "venite", "vengono"],
            "imperfetto": ["venivo", "venivi", "veniva", "venivamo", "venivate", "venivano"],
            "passato_prossimo": ["sono venuto", "sei venuto", "è venuto", "siamo venuti", "siete venuti", "sono venuti"],
            "futuro": ["verrò", "verrai", "verrà", "verremo", "verrete", "verranno"],
            "condizionale": ["verrei", "verresti", "verrebbe", "verremmo", "verreste", "verrebbero"],
            "congiuntivo_pres": ["venga", "venga", "venga", "veniamo", "veniate", "vengano"],
            "congiuntivo_imp": ["venissi", "venissi", "venisse", "venissimo", "veniste", "venissero"],
            "imperativo": ["-", "vieni", "venga", "veniamo", "venite", "vengano"],
            "gerundio": "venendo",
            "participio_passato": "venuto"
        },
        {
            "infinitive": "potere",
            "cefr": "A1",
            "auxiliary": "avere/essere",
            "meaning": "to be able to, can",
            "presente": ["posso", "puoi", "può", "possiamo", "potete", "possono"],
            "imperfetto": ["potevo", "potevi", "poteva", "potevamo", "potevate", "potevano"],
            "passato_prossimo": ["ho potuto", "hai potuto", "ha potuto", "abbiamo potuto", "avete potuto", "hanno potuto"],
            "futuro": ["potrò", "potrai", "potrà", "potremo", "potrete", "potranno"],
            "condizionale": ["potrei", "potresti", "potrebbe", "potremmo", "potreste", "potrebbero"],
            "congiuntivo_pres": ["possa", "possa", "possa", "possiamo", "possiate", "possano"],
            "congiuntivo_imp": ["potessi", "potessi", "potesse", "potessimo", "poteste", "potessero"],
            "imperativo": ["-", "-", "-", "-", "-", "-"],
            "gerundio": "potendo",
            "participio_passato": "potuto"
        },
        {
            "infinitive": "volere",
            "cefr": "A1",
            "auxiliary": "avere/essere",
            "meaning": "to want",
            "presente": ["voglio", "vuoi", "vuole", "vogliamo", "volete", "vogliono"],
            "imperfetto": ["volevo", "volevi", "voleva", "volevamo", "volevate", "volevano"],
            "passato_prossimo": ["ho voluto", "hai voluto", "ha voluto", "abbiamo voluto", "avete voluto", "hanno voluto"],
            "futuro": ["vorrò", "vorrai", "vorrà", "vorremo", "vorrete", "vorranno"],
            "condizionale": ["vorrei", "vorresti", "vorrebbe", "vorremmo", "vorreste", "vorrebbero"],
            "congiuntivo_pres": ["voglia", "voglia", "voglia", "vogliamo", "vogliate", "vogliano"],
            "congiuntivo_imp": ["volessi", "volessi", "volesse", "volessimo", "voleste", "volessero"],
            "imperativo": ["-", "vogli", "voglia", "vogliamo", "vogliate", "vogliano"],
            "gerundio": "volendo",
            "participio_passato": "voluto"
        },
        {
            "infinitive": "dovere",
            "cefr": "A1",
            "auxiliary": "avere/essere",
            "meaning": "to have to, must, owe",
            "presente": ["devo", "devi", "deve", "dobbiamo", "dovete", "devono"],
            "imperfetto": ["dovevo", "dovevi", "doveva", "dovevamo", "dovevate", "dovevano"],
            "passato_prossimo": ["ho dovuto", "hai dovuto", "ha dovuto", "abbiamo dovuto", "avete dovuto", "hanno dovuto"],
            "futuro": ["dovrò", "dovrai", "dovrà", "dovremo", "dovrete", "dovranno"],
            "condizionale": ["dovrei", "dovresti", "dovrebbe", "dovremmo", "dovreste", "dovrebbero"],
            "congiuntivo_pres": ["debba", "debba", "debba", "dobbiamo", "dobbiate", "debbano"],
            "congiuntivo_imp": ["dovessi", "dovessi", "dovesse", "dovessimo", "doveste", "dovessero"],
            "imperativo": ["-", "-", "-", "-", "-", "-"],
            "gerundio": "dovendo",
            "participio_passato": "dovuto"
        },
        {
            "infinitive": "sapere",
            "cefr": "A1",
            "auxiliary": "avere",
            "meaning": "to know (facts/how to)",
            "presente": ["so", "sai", "sa", "sappiamo", "sapete", "sanno"],
            "imperfetto": ["sapevo", "sapevi", "sapeva", "sapevamo", "sapevate", "sapevano"],
            "passato_prossimo": ["ho saputo", "hai saputo", "ha saputo", "abbiamo saputo", "avete saputo", "hanno saputo"],
            "futuro": ["saprò", "saprai", "saprà", "sapremo", "saprete", "sapranno"],
            "condizionale": ["saprei", "sapresti", "saprebbe", "sapremmo", "sapreste", "saprebbero"],
            "congiuntivo_pres": ["sappia", "sappia", "sappia", "sappiamo", "sappiate", "sappiano"],
            "congiuntivo_imp": ["sapessi", "sapessi", "sapesse", "sapessimo", "sapeste", "sapessero"],
            "imperativo": ["-", "sappi", "sappia", "sappiamo", "sappiate", "sappiano"],
            "gerundio": "sapendo",
            "participio_passato": "saputo"
        },
        {
            "infinitive": "stare",
            "cefr": "A1",
            "auxiliary": "essere",
            "meaning": "to stay, be (health/state/position)",
            "presente": ["sto", "stai", "sta", "stiamo", "state", "stanno"],
            "imperfetto": ["stavo", "stavi", "stava", "stavamo", "stavate", "stavano"],
            "passato_prossimo": ["sono stato", "sei stato", "è stato", "siamo stati", "siete stati", "sono stati"],
            "futuro": ["starò", "starai", "starà", "staremo", "starete", "staranno"],
            "condizionale": ["starei", "staresti", "starebbe", "staremmo", "stareste", "starebbero"],
            "congiuntivo_pres": ["stia", "stia", "stia", "stiamo", "stiate", "stiano"],
            "congiuntivo_imp": ["stessi", "stessi", "stesse", "stessimo", "steste", "stessero"],
            "imperativo": ["-", "sta'", "stia", "stiamo", "state", "stiano"],
            "gerundio": "stando",
            "participio_passato": "stato"
        },
        {
            "infinitive": "dare",
            "cefr": "A1",
            "auxiliary": "avere",
            "meaning": "to give",
            "presente": ["do", "dai", "dà", "diamo", "date", "danno"],
            "imperfetto": ["davo", "davi", "dava", "davamo", "davate", "davano"],
            "passato_prossimo": ["ho dato", "hai dato", "ha dato", "abbiamo dato", "avete dato", "hanno dato"],
            "futuro": ["darò", "darai", "darà", "daremo", "darete", "daranno"],
            "condizionale": ["darei", "daresti", "darebbe", "daremmo", "dareste", "darebbero"],
            "congiuntivo_pres": ["dia", "dia", "dia", "diamo", "diate", "diano"],
            "congiuntivo_imp": ["dessi", "dessi", "desse", "dessimo", "deste", "dessero"],
            "imperativo": ["-", "da'", "dia", "diamo", "date", "diano"],
            "gerundio": "dando",
            "participio_passato": "dato"
        },
        {
            "infinitive": "dire",
            "cefr": "A1",
            "auxiliary": "avere",
            "meaning": "to say, tell",
            "presente": ["dico", "dici", "dice", "diciamo", "dite", "dicono"],
            "imperfetto": ["dicevo", "dicevi", "diceva", "dicevamo", "dicevate", "dicevano"],
            "passato_prossimo": ["ho detto", "hai detto", "ha detto", "abbiamo detto", "avete detto", "hanno detto"],
            "futuro": ["dirò", "dirai", "dirà", "diremo", "direte", "diranno"],
            "condizionale": ["direi", "diresti", "direbbe", "diremmo", "direste", "direbbero"],
            "congiuntivo_pres": ["dica", "dica", "dica", "diciamo", "diciate", "dicano"],
            "congiuntivo_imp": ["dicessi", "dicessi", "dicesse", "dicessimo", "diceste", "dicessero"],
            "imperativo": ["-", "di'", "dica", "diciamo", "dite", "dicano"],
            "gerundio": "dicendo",
            "participio_passato": "detto"
        },
        {
            "infinitive": "uscire",
            "cefr": "A1",
            "auxiliary": "essere",
            "meaning": "to go out, exit",
            "presente": ["esco", "esci", "esce", "usciamo", "uscite", "escono"],
            "imperfetto": ["uscivo", "uscivi", "usciva", "uscivamo", "uscivate", "uscivano"],
            "passato_prossimo": ["sono uscito", "sei uscito", "è uscito", "siamo usciti", "siete usciti", "sono usciti"],
            "futuro": ["uscirò", "uscirai", "uscirà", "usciremo", "uscirete", "usciranno"],
            "condizionale": ["uscirei", "usciresti", "uscirebbe", "usciremmo", "uscireste", "uscirebbero"],
            "congiuntivo_pres": ["esca", "esca", "esca", "usciamo", "usciate", "escano"],
            "congiuntivo_imp": ["uscissi", "uscissi", "uscisse", "uscissimo", "usciste", "uscissero"],
            "imperativo": ["-", "esci", "esca", "usciamo", "uscite", "escano"],
            "gerundio": "uscendo",
            "participio_passato": "uscito"
        },
        {
            "infinitive": "vedere",
            "cefr": "A1",
            "auxiliary": "avere",
            "meaning": "to see",
            "presente": ["vedo", "vedi", "vede", "vediamo", "vedete", "vedono"],
            "imperfetto": ["vedevo", "vedevi", "vedeva", "vedevamo", "vedevate", "vedevano"],
            "passato_prossimo": ["ho visto", "hai visto", "ha visto", "abbiamo visto", "avete visto", "hanno visto"],
            "futuro": ["vedrò", "vedrai", "vedrà", "vedremo", "vedrete", "vedranno"],
            "condizionale": ["vedrei", "vedresti", "vedrebbe", "vedremmo", "vedreste", "vedrebbero"],
            "congiuntivo_pres": ["veda", "veda", "veda", "vediamo", "vediate", "vedano"],
            "congiuntivo_imp": ["vedessi", "vedessi", "vedesse", "vedessimo", "vedeste", "vedessero"],
            "imperativo": ["-", "vedi", "veda", "vediamo", "vedete", "vedano"],
            "gerundio": "vedendo",
            "participio_passato": "visto"
        },
        {
            "infinitive": "parlare",
            "cefr": "A1",
            "auxiliary": "avere",
            "meaning": "to speak, talk (regular -are model)",
            "presente": ["parlo", "parli", "parla", "parliamo", "parlate", "parlano"],
            "imperfetto": ["parlavo", "parlavi", "parlava", "parlavamo", "parlavate", "parlavano"],
            "passato_prossimo": ["ho parlato", "hai parlato", "ha parlato", "abbiamo parlato", "avete parlato", "hanno parlato"],
            "futuro": ["parlerò", "parlerai", "parlerà", "parleremo", "parlerete", "parleranno"],
            "condizionale": ["parlerei", "parleresti", "parlerrebbe", "parleremmo", "parlereste", "parlerebbero"],
            "congiuntivo_pres": ["parli", "parli", "parli", "parliamo", "parliate", "parlino"],
            "congiuntivo_imp": ["parlassi", "parlassi", "parlasse", "parlassimo", "parlaste", "parlassero"],
            "imperativo": ["-", "parla", "parli", "parliamo", "parlate", "parlino"],
            "gerundio": "parlando",
            "participio_passato": "parlato"
        },
        {
            "infinitive": "prendere",
            "cefr": "A1",
            "auxiliary": "avere",
            "meaning": "to take, have (food/drink)",
            "presente": ["prendo", "prendi", "prende", "prendiamo", "prendete", "prendono"],
            "imperfetto": ["prendevo", "prendevi", "prendeva", "prendevamo", "prendevate", "prendevano"],
            "passato_prossimo": ["ho preso", "hai preso", "ha preso", "abbiamo preso", "avete preso", "hanno preso"],
            "futuro": ["prenderò", "prenderai", "prenderà", "prenderemo", "prenderete", "prenderanno"],
            "condizionale": ["prenderei", "prenderesti", "prenderebbe", "prenderemmo", "prendereste", "prenderebbero"],
            "congiuntivo_pres": ["prenda", "prenda", "prenda", "prendiamo", "prendiate", "prendano"],
            "congiuntivo_imp": ["prendessi", "prendessi", "prendesse", "prendessimo", "prendeste", "prendessero"],
            "imperativo": ["-", "prendi", "prenda", "prendiamo", "prendete", "prendano"],
            "gerundio": "prendendo",
            "participio_passato": "preso"
        },
        {
            "infinitive": "dormire",
            "cefr": "A1",
            "auxiliary": "avere",
            "meaning": "to sleep (regular -ire model)",
            "presente": ["dormo", "dormi", "dorme", "dormiamo", "dormite", "dormono"],
            "imperfetto": ["dormivo", "dormivi", "dormiva", "dormivamo", "dormivate", "dormivano"],
            "passato_prossimo": ["ho dormito", "hai dormito", "ha dormito", "abbiamo dormito", "avete dormito", "hanno dormito"],
            "futuro": ["dormirò", "dormirai", "dormirà", "dormiremo", "dormirete", "dormiranno"],
            "condizionale": ["dormirei", "dormiresti", "dormirebbe", "dormiremmo", "dormireste", "dormirebbero"],
            "congiuntivo_pres": ["dorma", "dorma", "dorma", "dormiamo", "dormiate", "dormano"],
            "congiuntivo_imp": ["dormissi", "dormissi", "dormisse", "dormissimo", "dormiste", "dormissero"],
            "imperativo": ["-", "dormi", "dorma", "dormiamo", "dormite", "dormano"],
            "gerundio": "dormendo",
            "participio_passato": "dormito"
        },
        {
            "infinitive": "capire",
            "cefr": "A1",
            "auxiliary": "avere",
            "meaning": "to understand (-isc- inchoative model)",
            "presente": ["capisco", "capisci", "capisce", "capiamo", "capite", "capiscono"],
            "imperfetto": ["capivo", "capivi", "capiva", "capivamo", "capivate", "capivano"],
            "passato_prossimo": ["ho capito", "hai capito", "ha capito", "abbiamo capito", "avete capito", "hanno capito"],
            "futuro": ["capirò", "capirai", "capirà", "capiremo", "capirete", "capiranno"],
            "condizionale": ["capirei", "capiresti", "capirebbe", "capiremmo", "capireste", "capirebbero"],
            "congiuntivo_pres": ["capisca", "capisca", "capisca", "capiamo", "capiate", "capiscano"],
            "congiuntivo_imp": ["capissi", "capissi", "capisse", "capissimo", "capiste", "capissero"],
            "imperativo": ["-", "capisci", "capisca", "capiamo", "capite", "capiscano"],
            "gerundio": "capendo",
            "participio_passato": "capito"
        },
        {
            "infinitive": "bere",
            "cefr": "A1",
            "auxiliary": "avere",
            "meaning": "to drink",
            "presente": ["bevo", "bevi", "beve", "beviamo", "bevete", "bevono"],
            "imperfetto": ["bevevo", "bevevi", "beveva", "bevevamo", "bevevate", "bevevano"],
            "passato_prossimo": ["ho bevuto", "hai bevuto", "ha bevuto", "abbiamo bevuto", "avete bevuto", "hanno bevuto"],
            "futuro": ["berrò", "berrai", "berrà", "berremo", "berrete", "berranno"],
            "condizionale": ["berrei", "berresti", "berrebbe", "berremmo", "berreste", "berrebbero"],
            "congiuntivo_pres": ["beva", "beva", "beva", "beviamo", "beviate", "bevano"],
            "congiuntivo_imp": ["bevessi", "bevessi", "bevesse", "bevessimo", "beveste", "bevessero"],
            "imperativo": ["-", "bevi", "beva", "beviamo", "bevete", "bevano"],
            "gerundio": "bevendo",
            "participio_passato": "bevuto"
        },
        {
            "infinitive": "scegliere",
            "cefr": "B1",
            "auxiliary": "avere",
            "meaning": "to choose, pick",
            "presente": ["scelgo", "scegli", "sceglie", "scegliamo", "scegliete", "scelgono"],
            "imperfetto": ["sceglievo", "sceglievi", "sceglieva", "sceglievamo", "sceglievate", "sceglievano"],
            "passato_prossimo": ["ho scelto", "hai scelto", "ha scelto", "abbiamo scelto", "avete scelto", "hanno scelto"],
            "futuro": ["sceglierò", "sceglierai", "sceglierà", "sceglieremo", "sceglierete", "sceglieranno"],
            "condizionale": ["sceglierei", "sceglieresti", "sceglierebbe", "sceglieremmo", "scegliereste", "sceglierebbero"],
            "congiuntivo_pres": ["scelga", "scelga", "scelga", "scegliamo", "scegliate", "scelgano"],
            "congiuntivo_imp": ["scegliessi", "scegliessi", "scegliesse", "scegliessimo", "sceglieste", "scegliessero"],
            "imperativo": ["-", "scegli", "scelga", "scegliamo", "scegliete", "scelgano"],
            "gerundio": "scegliendo",
            "participio_passato": "scelto"
        },
        {
            "infinitive": "rimanere",
            "cefr": "A2",
            "auxiliary": "essere",
            "meaning": "to remain, stay",
            "presente": ["rimango", "rimani", "rimane", "rimaniamo", "rimanete", "rimangono"],
            "imperfetto": ["rimanevo", "rimanevi", "rimaneva", "rimanevamo", "rimanevate", "rimanevano"],
            "passato_prossimo": ["sono rimasto", "sei rimasto", "è rimasto", "siamo rimasti", "siete rimasti", "sono rimasti"],
            "futuro": ["rimarrò", "rimarrai", "rimarrà", "rimarremo", "rimarrete", "rimarranno"],
            "condizionale": ["rimarrei", "rimarresti", "rimarrebbe", "rimarremmo", "rimarreste", "rimarrebbero"],
            "congiuntivo_pres": ["rimanga", "rimanga", "rimanga", "rimaniamo", "rimaniate", "rimangano"],
            "congiuntivo_imp": ["rimanessi", "rimanessi", "rimanesse", "rimanessimo", "rimaneste", "rimanessero"],
            "imperativo": ["-", "rimani", "rimanga", "rimaniamo", "rimanete", "rimangano"],
            "gerundio": "rimanendo",
            "participio_passato": "rimasto"
        },
        {
            "infinitive": "piacere",
            "cefr": "A1",
            "auxiliary": "essere",
            "meaning": "to like, be pleasing to",
            "presente": ["piaccio", "piaci", "piace", "piacciamo", "piacete", "piacciono"],
            "imperfetto": ["piacevo", "piacevi", "piaceva", "piacevamo", "piacevate", "piacevano"],
            "passato_prossimo": ["sono piaciuto", "sei piaciuto", "è piaciuto", "siamo piaciuti", "siete piaciuti", "sono piaciuti"],
            "futuro": ["piacerò", "piacerai", "piacerà", "piaceremo", "piacerete", "piaceranno"],
            "condizionale": ["piacerei", "piaceresti", "piacerebbe", "piaceremmo", "piacereste", "piacerebbero"],
            "congiuntivo_pres": ["piaccia", "piaccia", "piaccia", "piacciamo", "piacciate", "piacciano"],
            "congiuntivo_imp": ["piacessi", "piacessi", "piacesse", "piacessimo", "piaceste", "piacessero"],
            "imperativo": ["-", "-", "-", "-", "-", "-"],
            "gerundio": "piacendo",
            "participio_passato": "piaciuto"
        }
    ]

    persons = [
        "1.ª pers. sing. (io)",
        "2.ª pers. sing. (tu)",
        "3.ª pers. sing. (lui/lei/Lei)",
        "1.ª pers. plur. (noi)",
        "2.ª pers. plur. (voi)",
        "3.ª pers. plur. (loro)"
    ]

    verb_paradigms = {}

    for v in verbs_data:
        inf = v["infinitive"]
        verb_paradigms[inf] = v

        # Add infinitive to dict
        if inf not in word_dict:
            word_dict[inf] = {
                "l": inf,
                "c": v["cefr"],
                "p": "v",
                "g": "",
                "m": v["meaning"],
                "t": "Infinito"
            }

        # Add gerundio
        ger = v["gerundio"]
        if ger not in word_dict:
            word_dict[ger] = {
                "l": inf,
                "c": v["cefr"],
                "p": "v",
                "g": "",
                "m": f"{v['meaning']} (gerundio)",
                "t": "Gerundio"
            }

        # Add participio passato
        pp = v["participio_passato"]
        if pp not in word_dict:
            word_dict[pp] = {
                "l": inf,
                "c": v["cefr"],
                "p": "v",
                "g": "m.sg",
                "m": f"{v['meaning']} (participio passato)",
                "t": "Participio Passato"
            }
        # Feminine & plural forms of participio passato
        if pp.endswith("o"):
            base = pp[:-1]
            for suff, g in [("a", "f.sg"), ("i", "m.pl"), ("e", "f.pl")]:
                form = base + suff
                if form not in word_dict:
                    word_dict[form] = {
                        "l": inf,
                        "c": v["cefr"],
                        "p": "v",
                        "g": g,
                        "m": f"{v['meaning']} (participio passato)",
                        "t": "Participio Passato"
                    }

        # Map tense lists
        tense_map = [
            ("presente", "Presente Indicativo"),
            ("imperfetto", "Imperfetto Indicativo"),
            ("futuro", "Futuro Semplice"),
            ("condizionale", "Condizionale Presente"),
            ("congiuntivo_pres", "Congiuntivo Presente"),
            ("congiuntivo_imp", "Congiuntivo Imperfetto"),
            ("imperativo", "Imperativo")
        ]

        for tense_key, tense_name in tense_map:
            forms = v.get(tense_key, [])
            for idx, form in enumerate(forms):
                if form and form != "-":
                    # Some forms can be identical across persons (e.g. sia, fossi)
                    p_name = persons[idx]
                    if form not in word_dict:
                        word_dict[form] = {
                            "l": inf,
                            "c": v["cefr"],
                            "p": "v",
                            "g": "",
                            "m": f"{v['meaning']} [{tense_name}]",
                            "t": tense_name,
                            "pn": p_name
                        }

    print(f"Total vocabulary and inflection entries compiled: {len(word_dict)}")
    print(f"Total full verb paradigms compiled: {len(verb_paradigms)}")

    # 3. Export to javascript file
    js_content = f"""// Italian CEFR & Conjugation Database
// Comprehensive CEFR A1-C2 vocabulary, RAE/Crusca phonetics, and complete verb paradigms
window.ITALIAN_DICT = {json.dumps(word_dict, ensure_ascii=False)};

window.ITALIAN_VERB_PARADIGMS = {json.dumps(verb_paradigms, ensure_ascii=False)};

window.ITALIAN_THEMES = [
  "Identità e Relazioni",
  "Esperienze e Viaggi",
  "Arte e Creatività",
  "Organizzazione Sociale",
  "Scienza e Ambiente"
];
"""

    out_path = os.path.join(os.path.dirname(__file__), "italian_data.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"Successfully generated {out_path} ({os.path.getsize(out_path)} bytes)")

if __name__ == "__main__":
    main()
